<?php
/**
 * Copyright (C) 2021 Tencent Cloud.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

namespace App\Modules\ThreadTom\Busi;


use App\Modules\ThreadTom\TomBaseBusi;

class VideoBusi extends TomBaseBusi
{

    public function create()
    {
        $videoIds = $this->getParams('videoIds');
        return $this->jsonReturn([
            [
                'id' => 7,
                'status' => 2,
                'reason' => '',
                'file_name' => '6431_20210326145913.mp3',
                'file_id' => '5285890816022158715',
                'height' => 0,
                'width' => 0,
                'duration' => '0.00',
                'media_url' => 'http://1500003868.vod2.myqcloud.com/6c9938c1vodcq1500003868/53f676885285890816022158715/h3WwJ20JpZcA.mp3',
                'cover_url' => ''
            ],
            [
                'id' => 6,
                'status' => 1,
                'reason' => '',
                'file_name' => '流火行者 2021-01-01 10.18.38.mp4',
                'file_id' => '5285890814874837502',
                'height' => 634,
                'width' => 360,
                'duration' => '7.81',
                'media_url' => 'http://1500003868.vod2.myqcloud.com/43832669vodtranscq1500003868/3731d4935285890814874837502/v.f100010.mp4',
                'cover_url' => 'http://1500003868.vod2.myqcloud.com/43832669vodtranscq1500003868/3731d4935285890814874837502/animatedGraphics/v.f20000.gif'
            ]
        ]);
    }

    public function delete()
    {
        parent::delete(); // TODO: Change the autogenerated stub
    }

    public function update()
    {
        return $this->jsonReturn([
            'name' => 'videoBusi'
        ]);
    }

    public function select()
    {
        return $this->jsonReturn([
            [
                'status' => 2,
                'reason' => '',
                'file_name' => '6431_20210326145913.mp3',
                'file_id' => '5285890816022158715',
                'height' => 0,
                'width' => 0,
                'duration' => '0.00',
                'media_url' => 'http://1500003868.vod2.myqcloud.com/6c9938c1vodcq1500003868/53f676885285890816022158715/h3WwJ20JpZcA.mp3',
                'cover_url' => ''
            ],
            [
                'status' => 1,
                'reason' => '',
                'file_name' => '流火行者 2021-01-01 10.18.38.mp4',
                'file_id' => '5285890814874837502',
                'height' => 634,
                'width' => 360,
                'duration' => '7.81',
                'media_url' => 'http://1500003868.vod2.myqcloud.com/43832669vodtranscq1500003868/3731d4935285890814874837502/v.f100010.mp4',
                'cover_url' => 'http://1500003868.vod2.myqcloud.com/43832669vodtranscq1500003868/3731d4935285890814874837502/animatedGraphics/v.f20000.gif'
            ]
        ]);
    }
}
